services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '2000:3000'
    networks:
      - cclemon-network   
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}

networks:
  cclemon-network:
    external: true