server:
  port: 8884

kafka:
  topic: TEST

spring:
  kafka:
    bootstrap-servers: localhost:9093,localhost:9095,localhost:9097
  jpa:
    hibernate:
      ddl-auto: update  # 可選 create / update / none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/cclemon-health?allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei&useSSL=false
    username: root
    password: P@ssw0rd
    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

authorization-server:
  url: http://localhost:9000
cclemon-ui:
  url: http://127.0.0.1:5173