properties([
  parameters([
    choice(name: 'TYPE', choices: ['build', 'deploy'], description: '執行類型'),
    string(name: 'PROJECT_NAME', defaultValue: 'cclemon-auth', description: '專案'),
    choice(name: 'PROFILE', choices: ['dev', 'prod'], description: '環境')
  ])
])


pipeline {
  agent {
    dockerfile {
      dir 'ci'
      args '-v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.gradle:/home/gradle/.gradle'
    }
  }

  environment {
    TZ = 'Asia/Taipei'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
        sh 'chmod +x gradlew'
      }
    }

    stage('Build') {
      when {
        expression { return params.BUILD_TYPE == 'build' }
      }
      steps {
        dir("${params.PROJECT_DIR}") {
          sh "../gradlew clean build -x test -Pprofile=${params.BUILD_PROFILE}"
        }
      }
    }

    stage('Archive Jar') {
      when {
        expression { return params.BUILD_TYPE == 'build' }
      }
      steps {
        archiveArtifacts artifacts: "${params.PROJECT_DIR}/build/libs/*.jar", fingerprint: true
      }
    }

    stage('Build Docker Image') {
      when {
        expression { return params.BUILD_TYPE == 'build' }
      }
      steps {
        dir("${params.PROJECT_DIR}") {
          script {
            def imageName = "${params.PROJECT_DIR}"
            def imageTag = "${params.BUILD_PROFILE}"
            sh "docker build -t ${imageName}:${imageTag} ."
          }
        }
      }
    }

    stage('Deploy') {
      when {
        expression { return params.BUILD_TYPE == 'deploy' }
      }
      steps {
        echo "Deploying ${params.PROJECT_DIR} with profile ${params.BUILD_PROFILE}"
        // 可加上實際部署腳本或指令
        sh "docker-compose up"
      }
    }
  }
}
