spring:
  application:
    name: cclemon-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anderson-chen/cclemon-config-repo
#          repos:
#            - patterns: multi-repo-demo-*
#              uri: https://github.com/spring-cloud-samples/config-repo
  kafka:
    bootstrap-servers: localhost:9093,localhost:9095,localhost:9097

server:
  port: 8555

management:
  endpoints:
    web:
      exposure:
        include: busrefresh , busshutdown , health